### ISSUE TITLE
add  'Complete these assignments' before the list of assignments 1,2,3 etc.  

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#10]
add  'Complete these assignments' before the list of assignments 1,2,3 etc.  to be consistent with the earlier blocks 'watch this animation' ,' take this quiz '  'watch this interactive animation' ,

**Comment by frederic-reis** [comment]
Can I put "COMPLETE ASSIGNMENT #1", "COMPLETE ASSIGNMENT #2" for each assignment ?

**Comment by stefaniascagliola** [comment]
Well, maybe that is too invasive (impression of being to much a teacher who forces you to do things)
maybe it is better to only put it  only 1 time at the top of the assignments.

**Comment by frederic-reis** [comment]
Ok. In this case, can I remove titles "ASSIGNMENT #1", "ASSIGNMENT #2", ... ?

**Comment by stefaniascagliola** [comment]
yes, you can!!!!

**Comment by frederic-reis** [comment]
It's done!
