### ISSUE TITLE
new pull request for new added documents 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#104]
- I reformatted and re-designed the Fr and Ger tutorials for assignment 6 and 7 of Arch to Digital 
- I reformatted the Answer templates for lesson Boder and Arch to Digital Turn. 
- gave them all names without capitals and symbols 
<img width="316" alt="screen shot 2018-11-30 at 15 17 05" src="https://user-images.githubusercontent.com/33933280/49294805-498bf600-f4b4-11e8-976c-83a68e7c6ac6.png">
- uploaded these documents in assets 
- gave pdfs a slug in Google sheets 
- have not done so with WORD documents 
- added the documents in metadata of.  assignments 6 and 7 Fr and Ger of lesson Archival to Digital - - - added new answer template at lesson level for French and German version, (they are not translated, they are the same as in English, wait to see whether there is need for translation ) 

Request to Fred: could you make a pull request to change/add the documents on the website?

**Comment by frederic-reis** [comment]
I made a little check before running the script.

* In the Google Sheet, you didn't define a title for new records.
* The name of the pdf in the attachment field (`examplereponse.pdf`)  doesn't match the name of the file (`exemple_reponse_affectation_journaux.pdf`).

**Comment by stefaniascagliola** [comment]
just fixed these points (I hope?)

**Comment by frederic-reis** [comment]
I ran the script to fill the `_data/documents.yaml` file
