### ISSUE TITLE
answer templates 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#106]
Hi Fred,

I have just done a review of lesson Archival to Digital to check wether everything works, and I have found a few flaws that I cannot solve on my own.
The WORD documents of both the answer template for lesson Archival to Digital as for Boder give an error code when you try to download them. They have a slug in the Google Tables: https://docs.google.com/spreadsheets/d/1kRGo8pfsXjugWRRM3H5T2Ew-sHtGiqDPH0grV74y5MA/edit?usp=sharing , they are uploaded in assets/pdf, and they used to work perfectly, so something must have been altered, could you check?
best Stefania

**Comment by frederic-reis** [comment]
It's fixed.
Duplicate with #66.
