### ISSUE TITLE
replace all clips with version with jingle and logo 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#108]
Dear Fred, 

I need your help again. 
To meet the requirements of the central Communication Department, who will publish the clips of Ranke 2 on Youtube, we had to add the jingle at the beginning and logo at the end of every clip.
Cristina has done this job. Noelle has replaced the existing clips on VIMEO with the new ones and added versions that were no there yet. 
I have tried to replace the SRCs in the folder I-frames.yaml , sometimes it is immediately visible on the website, sometimes it is not. Noelle has created a document with all the new urls, and I have written in the document, what is ok, and what is still missing. 
It may be because you still have to 'pull' the new version, to be able to see it online. But there might be some other errors. I did not dare add a new clip, as there are all kinds of metadata that should be completed, and Ihave no clue. I am afraid of creating chaos, because of some small things missing. 
Could you fix this problem?

best wishes, 
Stefania
[SS_Links and codes on Vimeo v2.docx](https://github.com/C2DH/ranketwo/files/2793966/SS_Links.and.codes.on.Vimeo.v2.docx)

**Comment by frederic-reis** [comment]
It's fixed. You forgot quotes at the end of the src property of the first clip in the iframe file.

Could you check if it's ok ?

**Comment by stefaniascagliola** [comment]
Archival to Digital is ok in all languages


Boder is Ok in all languages


Transformation is Ok in all languages


Dalimil is missing in all languages, Vimeo link has to be entered into GitHub


Lars Webtechnology is missing in German and French

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: vrijdag 25 januari 2019 11:36:43
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Author
Onderwerp: Re: [C2DH/ranketwo] replace all clips with version with jingle and logo (#108)


It's fixed. You forgot quotes at the end of the src property of the first clip in the iframe file.

Could you check if it's ok ?

**Comment by frederic-reis** [comment]
I added missing clips.

Could you check if it's ok ?

**Comment by stefaniascagliola** [comment]
it all works fine!!!!!

Now I have to sort out how to adapt the texts around the clips,

will try myself, and then ask your help if I get lost


best

Stefania

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: vrijdag 25 januari 2019 17:57:37
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Author
Onderwerp: Re: [C2DH/ranketwo] replace all clips with version with jingle and logo (#108)


I added missing clips.

Could you check if it's ok ?

**Comment by frederic-reis** [comment]
@stefaniascagliola 

I don't know what is the procedure for the thumbnail. I see in the `iframe.yaml` file that the thumbnail is on the vimeo platform for Boder and Boder2 units and on github for archival unit.
