### ISSUE TITLE
another replacement of the titles of the main page

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#11]
Hi Fred, 
I just had a talk with my boss Gerben, who would like the titles to be shorter, in view of people who view the screen on a computer with a smaller size. 
So this means that the titles have to be changed:
Sorry ;))))

About the project =                                    About
Structure of the Teaching Modules =       Structure of Lessons
Content of the Teaching Modules =         Content of Lessons
How to define Digital Source Criticism = Defining Digital Source Criticism

**Comment by danieleguido** [comment]
@stefaniascagliola you can just change the `title` fields in [navigation.yaml](https://github.com/C2DH/ranketwo/blob/master/_data/navigation.yaml)

**Comment by stefaniascagliola** [comment]
ok
