### ISSUE TITLE
pull request

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#110]
I have changed various short sentences that still needed to be translated, but they don't show on the website, I think you have to do a pull request, or I did something wrong, 
best
Stefania

Could you check another time, after the pull, to see whether there are still passages untranslated?

**Comment by frederic-reis** [comment]
There were an issue with the automatic deploy of the website.

The issue should be fixed by @danieleguido. Could you check if it's ok now ?
