### ISSUE TITLE
integrating pdfs of presentations in page 'expert meeting' and 'skill training' sub pages of 'defining source criticism' 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#111]
Dear Fred, 

I have created slugs for 4 pdfs of the expert meeting (see pink rows)

and for 3 pdfs FOR the skill training (see blue rows) 

https://docs.google.com/spreadsheets/d/1kRGo8pfsXjugWRRM3H5T2Ew-sHtGiqDPH0grV74y5MA/edit?usp=sharing 

I have tried to enter every pdf into assets - pdf, but two documents are not accepted:

scagliola-skilltraining-dsc
--
dwyer-skilltraining-dsc

because they are too big,  I don't know how to solve the issues, as I don't think it works to zip the pdfs, 

I am sending them to you through wetransfer - or maybe we should make an exception and put in a link to google doc? 

in Github you will find these pages: 

ranketwo/pages/define-expert-meeting.md 
ranketwo/pages/define-dsc-skilltraining.md 

in all the places in which a link to the pdf should be inserted you will find this text in brackets: 

(TURN TITLE INTO LINK TO PDF OF........) 

 hope this is all clear, 

best
Stefania

**Comment by frederic-reis** [comment]
I added both files on github.
I also renamed them in `scagliola-skilltraining-dsc.pdf` and `dwyer-skilltraining-dsc.pdf`. Is it ok for you ?
