### ISSUE TITLE
added literature in google sheets with slugs 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#112]
Dear Fred, 

I have added two articles to the list that we already have, in the tab Static Pages Literature

https://docs.google.com/spreadsheets/d/1kRGo8pfsXjugWRRM3H5T2Ew-sHtGiqDPH0grV74y5MA/edit#gid=1652775452

see items on row 19 and 20, 

could you make sure that they are integrated in GitHub and appear on the website? 

 the first author Foehr should come after Fickers, and the second, Koolen et al, after Kirschbaum, 

I considered adding the data in 'documents/ymla, but remembered that Daniele told me not to mess in that folder, 

best wishes, 
Stefania

**Comment by frederic-reis** [comment]
It's done !
