### ISSUE TITLE
add thumbnail to lesson Dalimil on Manuscripts 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#114]
<img width="980" alt="Screenshot 2019-03-14 at 16 48 56" src="https://user-images.githubusercontent.com/33933280/54371176-3e329400-4679-11e9-9a46-00ee063c1e02.png">

**Comment by stefaniascagliola** [comment]
Hi Fred, 

could you add this image as a thumbnail for the Dalimil lesson?

**Comment by frederic-reis** [comment]
Hi @stefaniascagliola,

It's done!

**Comment by stefaniascagliola** [comment]
thanks!

S.

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: vrijdag 15 maart 2019 15:31:52
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Mention
Onderwerp: Re: [C2DH/ranketwo] add thumbnail to lesson Dalimil on Manuscripts (#114)


Hi @stefaniascagliola<https://github.com/stefaniascagliola>,

It's done!
