### ISSUE TITLE
create section for teaching materials

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ranketwo#116]
- [x] create page with title: "teaching aids"
- [x] prepare list teaching aids (pdf "Ranke2 in a nutshell", "how to collaborate", "visual aids" 4 images, "answer forms" 1 per lesson with link to the lesson)
- [ ] all pdf with instructions "how to create"

**Comment by stefaniascagliola** [comment]
the list of documents to add with the link to where they are stored:


- Didigital Source Criticism in a nutshell - handout about Ranke.2
- How to collaborate - guide on how to create teaching content for Ranke.2
- Visual aids - explain transformation from analog to digital 
- Answer form ' David Boder, from wire recorder to website'
- Answer form 'From archival to digital turn' 
- Tutorial 'Struggling with timelines'
- How to use the timeline tool TikiToki
- Tracing the publication date of web content; what works and what does not 
- Cheat sheet with search tips from Google 
 
I have entered these element in the code, will add links to content later on
