### ISSUE TITLE
new button in home page

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ranketwo#118]
Addd a button on the right side of the videos in home page towards the visual aids pdf
title:
special: What questions to ask to a source?

**Comment by stefaniascagliola** [comment]
Andreas prefers this wording:

Key questions to ask

**Comment by frederic-reis** [comment]
@danieleguido   Any idea for the design ?

**Comment by danieleguido** [comment]
Yep! 👍 I'm working on it
