### ISSUE TITLE
REPLACE titles of documents in teaching aids

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#119]
Hi Fred, 

can you make these changes, or ask Daniele how to go about? 

Have discussed this with Andreas some time ago.

this is about the page: https://ranke2.uni.lu/teaching-aids/ 
 
it is too messy now, Andreas asked for some changes: 

changes in titles: 

turn 'Digital Source Criticism in a Nutshel' into:  'Leaflet about Ranke.2'
turn 'How to Collaborate' into:   'Instructions on how to collaborate' 
turn 'Visual Aid' into: 'Handout for Teaching Digital Source Criticism' 

changes in structure 

one part is about  ...general documents... , the frist three documents belong to this part 

below that the documents should be grouped around a lesson: 

From Archival to Digital 
- answer form 
- what works and what does not
- cheat sheet with search tips from Google

David Boder 
- answer form 
- Struggling with Timelines
- How to use the Timeline tool Tiki Toki 

etc.

**Comment by frederic-reis** [comment]
Hi Stefania,

If I well understood, you would like me to create 3 groups on the page ?
* general documents
* From Archival to Digital
* David Boder

**Comment by stefaniascagliola** [comment]
yes, you got it!!!

Thanks

Stefania

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: donderdag 9 april 2020 17:13:41
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Author
Onderwerp: Re: [C2DH/ranketwo] REPLACE titles of documents in teaching aids (#119)


Hi Stefania,

If I well understood, you would like me to create 3 groups on the page ?

  *   general documents
  *   From Archival to Digital
  *   David Boder

**Comment by frederic-reis** [comment]
@stefaniascagliola  Is it ok like that ?

I'll just need the General documents title in french and german.
