### ISSUE TITLE
order of the lessons in tab  'teaching' 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#12]
At present in the tab 'teaching'  you first have:

From the Archival to the Digital Turn

David Boder: From wire recorder to website 

Manuscripts; copies or original 

Transformation; How the digital creates new realities 

Can you change the order of the first two titles?

first                  Boder
second            From Archival to Digital Turn

**Comment by danieleguido** [comment]
@stefaniascagliola this can be done using the `order` property in the corresponding unit markdonw file. I modified the metadata of [boder.md](https://github.com/C2DH/ranketwo/blob/master/_units/boder.md)
