### ISSUE TITLE
create link to this PDF

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#120]
HI Fred, 

in the intro of the quiz about Boder there is the possibility to download the transcript of the animation, see: https://ranke2.uni.lu/u/boder/ 
To answer these questions you can consult the transcript of the voice-over that can be accessed through this link [NEED LINK TO PDF]. But first answer questions 1 to 6.

Could you add the PDF that is attached? 
[Storyboard Boder English.pdf](https://github.com/C2DH/ranketwo/files/4149128/Storyboard.Boder.English.pdf)

**Comment by frederic-reis** [comment]
It's done!
