### ISSUE TITLE
assignments text. also shows in right bar, where only learning outcomes should be

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#122]
Dear Fred,

I am struggling with finding out why the assignments appear in the centre, but also on the right side, where only the 'learning outcomes' should show.
Can you find out what I did wrong?

thanks, 
Stefania

**Comment by stefaniascagliola** [comment]
Sorry, I should have mentioned that this is about the new lesson about newspapers - from the shelf to the web, 
best
Stefania

**Comment by frederic-reis** [comment]
It's because it misses `<!-- briefing-teacher -->` at the end

**Comment by frederic-reis** [comment]
It misses too a space just before Instructions title
