### ISSUE TITLE
need for different fonts in running text 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#124]
HI Fred, 

In the intro of Exploring Newspapers , above the assignments (part of units)
I need to use original fonts, see this document
https://docs.google.com/document/d/1boIHTinuQootrxO-gw8LkNZ4SMjKboD_tR5gjzrmYO0/edit?usp=sharing 

Are these letters from a Latin alphabet or an Arabic one? 
Are the letters in italic or bold? 
Is the font Times New Roman or Comic Sans MS? 

How do I solve this in markdown?  See below for print screen,

S. 

best
Stefania

**Comment by stefaniascagliola** [comment]
<img width="756" alt="Screenshot 2020-04-08 at 16 25 31" src="https://user-images.githubusercontent.com/33933280/78795712-98ee0a80-79b5-11ea-9dce-b8c6cd6c4501.png">

**Comment by frederic-reis** [comment]
Hi Stefania,

It's done.
For italic and bold, it's easy. I just used the markdown syntax : `_italic text_ and **bold text**`
For fonts, I needed to use css stylesheet

**Comment by danieleguido** [comment]
hi @frederic-reis , no need to add fonts to the stylesheet, just add: `font-family:"Comic Sans MS", cursive, sans-serif` in inline style attribute

**Comment by frederic-reis** [comment]
Thank you. I know that. :)
It's just a choice.
