### ISSUE TITLE
subtitle of the lesson is just "impresso"

### ISSUE THREAD

**Issue by Bunoute** [C2DH/ranketwo#126]
also, the description of the clip is just "impresso".
could we add some more text? for instance, some text of the clip itself?
e.g.: 

From Chinese ink to digitised objects, changes in technology are creating a new future for yesterday’s news.
In this lesson, we propose three topics:
- The peculiarities of newspapers as historical sources
- The changes brought about by digitisation
- Methods for enriching newspapers that open up new ways of discovering content
Join us on a voyage of discovery as we explore the transformation of historical newspapers in the digital age!

**Comment by stefaniascagliola** [comment]
Hi Fred, 

if I go to this page in markdown, to change the text in the introduction, I don't have access, can you sort out why?


<img width="1157" alt="Screenshot 2020-04-07 at 18 18 58" src="https://user-images.githubusercontent.com/33933280/78795282-1feeb300-79b5-11ea-8f94-0e6330ab1454.png">

**Comment by frederic-reis** [comment]
It's because you are not on the master branch.
You need to click on the button `Tree: ff15960...` at the top left and select master.

**Comment by stefaniascagliola** [comment]
thanks!!!
