### ISSUE TITLE
adjust the tags for Boder

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#13]
Hi Fred, 

I have this problem: in UNIT Boder , there is the document  Boder.md,  I have included the tags 

Holocaust Studies, History of Communication technology etc,  but they appear in two places:

in the  first tab of TEACHING , where they belong

but they also appear in the second Tab of teaching, in the lesson of David Boder, below the header From Wire recorder to Website,  I would like to make them disappear here,

I think it is the same issue that we had with 'About the project'.

Can you help me out?

best
STefania

**Comment by frederic-reis** [comment]
It's done!

**Comment by stefaniascagliola** [comment]
thanks,great!!!!!
S.
