### ISSUE TITLE
the clip of Boder in the quiz app Playposit 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#14]
Somehow the link to the Playposit quiz based on the  clip on Boder, does not work,  here I have copied it again, hope that this one works: https://www.playposit.com/play/797374/David-Boders-Interview-collection-2-2

**Comment by frederic-reis** [comment]
Done !

**Comment by stefaniascagliola** [comment]
great!!!!! Well done!!!!
Stefania
