### ISSUE TITLE
subtitles for the French and German version of the Newspaper clip 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#140]
HI Daniele and Fred, 

I am not sure whether Fred is able to take this over from Daniele, but the next thing to do, is to create 2 new Vimeo clips with French and German subtitles of the Newspapers in the Digital Age clip. Enclosed you will find the documents sent to me by Maria Cristina. 
Can you let me know when you have time to arrange this? 

[2020.02.25 Ranke 2_From the shelf to the web_T_FR.docx](https://github.com/C2DH/ranketwo/files/4455576/2020.02.25.Ranke.2_From.the.shelf.to.the.web_T_FR.docx)
[2020.03.06 Ranke 2_From the shelf to the web_T_DE.docx](https://github.com/C2DH/ranketwo/files/4455577/2020.03.06.Ranke.2_From.the.shelf.to.the.web_T_DE.docx)

**Comment by danieleguido** [comment]
Hi @stefaniascagliola, the transcripts don't contain any time related info.
We can use https://amara.org/en/ but I don't know if it worths the effort, it can be a looong process! What do we do?

**Comment by stefaniascagliola** [comment]
how have we dealt with this with the other clips? I don't recall the need to add time stamps to the sentences, I will trace back the time schedule of the animation, if I add another column and put the sentences at the right time, would that help?
