### ISSUE TITLE
how can I create a folder in the folder with images, 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#145]
`I have uploaded a lot of images for assignment 1.c of the lesson Transformation in GitHub - images. how can I create a folder, and put all the images in that folder , so that it becomes clear that they belong to each other ???
best wishes,
Stefania

**Comment by frederic-reis** [comment]
Hi Stefania,

Manipulation of images file on the web interface of github is very limited. You cannot directly move or rename them. You need to delete them and upload them again

The same for folders. You cannot create an empty folder. To create a folder, you need to create a new empty file specifying the folder. Then you upload your image files. Finally, you can remove the empty file. Some explanations here : https://github.community/t/add-a-folder/2304

So, I created a transformation folder for you and I moved images into . Tell me if you want a subfolder like by example assignment1c and I can do it for you.

One more thing. I renamed some images. On the web, a best practices is to only use lowercase letters, dashes and dot in filename. It's also better to use explicit name for files and avoid screenshot.

Fred

**Comment by frederic-reis** [comment]
Here is the new folder : https://github.com/C2DH/ranketwo/tree/master/assets/images/transformation

**Comment by stefaniascagliola** [comment]
Dear Fred,


thank you very much for your explanation, in fact, I would like you to create separate folders for images that belong to separate assignments, so that Daniele or you know which. image has to be re-sized and put into the table of the assignment, I have deleted the images with no name in GitHub and reloaded them with names.


1b - screenshot. of google-image and tineye


1c - image of. example; painting of Dora Maar by Picasso,

a lot of images of various kinds :

Obama, boyinblue, Charles Darwin, post Morten man, postmortem children, Botticelli , man mask, woman in labor, Botticelli , morel, Oscar Wilde


3b - ngram


3 d - images of paintings with mythological figures;

Diana Callisto

joahnn Kong

John. willim waterhouse

noel Nicolas

the master of the judge


could you rearrange the. images. in these different folders, and discuss with Daniele how to put them in place?


if you want an example of how it should look,  take a look here:


https://docs.google.com/document/d/1CP7FRs0uTpR1PVBm0Bn6KLtzMYzZ3N7WrZVt654ddMY/edit?usp=sharing.


best wishes

Stefania


Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: dinsdag 7 juli 2020 12:19:28
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Author
Onderwerp: Re: [C2DH/ranketwo] how can I create a folder in the folder with images, (#145)


Here is the new folder : https://github.com/C2DH/ranketwo/tree/master/assets/images/transformation

**Comment by frederic-reis** [comment]
I rearranged the images in subfolders

**Comment by frederic-reis** [comment]
Hi @stefaniascagliola, the google search and tineye images are the same.  The google search image is wrong.

**Comment by stefaniascagliola** [comment]
I substituted the wrong image, it is now in the folder,

best

Stefania

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: woensdag 8 juli 2020 11:26:11
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Mention
Onderwerp: Re: [C2DH/ranketwo] how can I create a folder in the folder with images, (#145)


Hi @stefaniascagliola<https://github.com/stefaniascagliola>, the google search and tineye images are the same. The google search image is wrong.

**Comment by frederic-reis** [comment]
I've inserted images on the first assignment. Could you check if it's ok like that ?

**Comment by stefaniascagliola** [comment]
Hi Fred,


thanks, we are on the good track,

I have included a screenshot in the attachment, to indicate where the two screenshots should go in assignment 1b.

hope this is clear,

will send separate e-mails for separate issues,

best

Stefania








Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: woensdag 8 juli 2020 19:15:04
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Mention
Onderwerp: Re: [C2DH/ranketwo] how can I create a folder in the folder with images, (#145)


I've inserted images on the first assignment. Could you check if it's ok like that ?

**Comment by stefaniascagliola** [comment]
hi Fred,


in assignment 1c I miss OSCAR WILDE, BOY WITH BLUE SLEEVE, AND POST MORTEM MAN,

they were not in the google doc, but I have added them later, can you add them? Is it possible to add them in a way, that if you click on them you get a larger size of the image in your browser?


best

Stefania

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: Stefania SCAGLIOLA
Verzonden: donderdag 9 juli 2020 13:08:48
Aan: C2DH/ranketwo
Onderwerp: Re: [C2DH/ranketwo] how can I create a folder in the folder with images, (#145)


Hi Fred,


thanks, we are on the good track,

I have included a screenshot in the attachment, to indicate where the two screenshots should go in assignment 1b.

hope this is clear,

will send separate e-mails for separate issues,

best

Stefania








Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: woensdag 8 juli 2020 19:15:04
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Mention
Onderwerp: Re: [C2DH/ranketwo] how can I create a folder in the folder with images, (#145)


I've inserted images on the first assignment. Could you check if it's ok like that ?

**Comment by frederic-reis** [comment]
Sorry, I can't see your attachment

**Comment by frederic-reis** [comment]
I added the Postmortem man picture and the feature when you click on pictures the original size opens in a new tab
