### ISSUE TITLE
Digital Transformation - assignment 1 a. upload PDF with EXIF metadata explanation

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#148]
[SS_Exif data in Mac and Windows.pdf]

create link in text ' click here for access to a PDF xxxxx' see screenshot 

(https://github.com/C2DH/ranketwo/files/5674691/SS_Exif.data.in.Mac.and.Windows.pdf)

<img width="645" alt="Screenshot 2020-12-10 at 16 47 09" src="https://user-images.githubusercontent.com/33933280/101809495-e78d0f00-3b17-11eb-887d-4fea27aa0b81.png">

**Comment by frederic-reis** [comment]
Done in english!
There is no text yet for french and german.

**Comment by stefaniascagliola** [comment]
yes, you are right, I want to first arrange everything in English, Thanks!!!!!

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: donderdag 17 december 2020 17:50:23
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Author
Onderwerp: Re: [C2DH/ranketwo] Digital Transformation - assignment 1 a. upload PDF with EXIF metadata explanation (#148)


Done in english!
There is no text yet for french and german.
