### ISSUE TITLE
Digital Transformation assignment 1b Digital two images to explain interface Google and Tineye

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#149]
THIS IS THE TEXT IN THE ASSIGNMENT,  WITH THE PLACE WHERE THE TWO IMAGES SHOULD BE INCORPORATED.
 IF THIS IS A PROBLEM, YOU CAN SIZE THEM DOWN.

To understand how image recognition through computers evolved first, watch this TED Talk by scholar Fei Fei Li of Stanford University.Next, open one tab to Google Images, and another tab to Tineye and upload your screenshot from your desktop to both services. A summary of the retrieved results will appear, along with all the listed hits below.

![search1](https://user-images.githubusercontent.com/33933280/101810383-05a73f00-3b19-11eb-8230-e91f24815487.png)
![Search2](https://user-images.githubusercontent.com/33933280/101810396-08a22f80-3b19-11eb-9a5e-79b7d0448db5.png)

Complete the table with your findings. Put a copy of your screenshot in the first field (if you have chosen a portrait page setup, you will need to make it smaller to fit in the field)
Describe the differences in options to select between the two services
Describe the metadata components of the summary of the search in both services, paying attention to the differences between the two services. This includes things such as the dimensions of the image, possible related search terms, the file type, and any other information relating to the image itself.
Describe the metadata components of the search results in both services, paying attention to the differences between the two services. This includes things such as the titles and text of the websites that appear, the number of search results, and any other information relating to the search results generated by the different services.
Describe the first two search results, first the result of the search and then what you find when you open the link, assess the quality of the image recognition in both services.

**Comment by frederic-reis** [comment]
Done!
