### ISSUE TITLE
Digital Transformation - Assignment 1 c  image of Dora Maar is missing 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#150]
This is to show where it should come , is should fill the empty space next to the dead men and below the women in labor 

<img width="640" alt="Screenshot 2020-12-10 at 19 06 22" src="https://user-images.githubusercontent.com/33933280/101811775-cf6abf00-3b1a-11eb-9472-6e47aa505915.png">

![Dora Maar](https://user-images.githubusercontent.com/33933280/101811920-fa551300-3b1a-11eb-956a-596bd99a5443.png)

Additional remark, I just discovered that the image of Dora maar is already in Assets - images1!!!

**Comment by frederic-reis** [comment]
It's done.
