### ISSUE TITLE
Digital Transformation assignment 3d - small images when clicked on appear in new window in bigger size 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#151]
In assignment 1c when you click on the small images they appear in a bigger size in a new window. I would like the same effect with the small images in assignment 3d about metamorphoses 

<img width="629" alt="Screenshot 2020-12-10 at 19 11 11" src="https://user-images.githubusercontent.com/33933280/101812300-79e2e200-3b1b-11eb-9e61-c39b3070382d.png">

**Comment by frederic-reis** [comment]
It's done.
