### ISSUE TITLE
substitute broken audio links in assignments David Boder

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#152]
Dear Fred,

the following has happened; the website http://voices.iit.edu  about David Boder is in the course of being upgraded and has been taken off line . This means that 5 links in assignments to audio are broken (see the passages below) and that other issues hamper the making of another 4 assignments. For the none audio issues I have divided the tasks with my student assistants, in a emergency document. 

For the audio issues I would like the help of Fred. I have found the substitute website on the temporary platform created via aviary, but when I click on the button share to generate a link, it offers 4 different options and I don't know which one to choose. Could you help me out? The **bold text** is where the new link should be placed.
 
LESSON FROM WIRE TO WEB - DAVID BODER

**3.c**  A second exploration of the archives: how key characters are represented
•	Compare how a respondent describes the selection process for the gas chambers and the role of SS physician Mengele in protocol with how this is done in Boder’s I**interview with Jola Gross.**
INSERT URL - https://iit.aviaryplatform.com/r/2804x54p2z 
 
<img width="792" alt="Screenshot 2020-12-16 at 08 08 32" src="https://user-images.githubusercontent.com/33933280/102316260-e6c00700-3f75-11eb-85fd-d8b39e2872d6.png">

•	What strikes you as different between the summarised interview and the literal transcript of the interview?
•	Note the answer in your template.

**3.d** A third exploration of the archives: the identity of the speaker
•	Compare the protocol of a 15-year-old girl in http://degob.org/ (select Female and date of birth 1931 in the search environment) with listening to **Boder’s interview with 15-year-old Edith Ziere**r*. 
INSERT URL FRED - https://iit.aviaryplatform.com/r/0g3gx44z67

**8.a** Comparing a printed anonymous transcript to its digital version online
•	Read the interview with Jorn Gastfreund (alias Jurgen Bassfreund) with the short introduction by David Boder. It is 27 pages long. This is a digital scan of his printed book.
•	Now go to the Voices of the Holocaust website (use Chrome as your browser – it will allow you to accept Flash Player so that you can listen to the sound).
•	The URL looks like this:
 
•	click on the small “i” icon to configure your browser settings. Allow Flash Player  and pop ups by ticking the boxes.
•	Then click on **this link**: http://voices.iit.edu/interviewee?doc=bassfreundJ. 
 CHANGE URL FRED  https://iit.aviaryplatform.com/r/1r6n00zz2w 

•	First read the “Description" [is named 'commentary' in old text, should be 'description' in edited text]. Then click on “English translation”.
•	Read the text up to the sentence:
“I worked at that time on the railroad and the Hitler guard packed us into a truck and we were all driven to a distribution camp”

**12.a**  A child of 15 compared to a women of 70
•	What are the most striking differences between the interview in 1946 and the one in 2003?
•	Listen to to the **audio of Edith Zierer in German in 1946** and take notes.  
o	In the template there are instructions about what you should pay attention to.
o	If you don’t master German, open the English translation in another window. 

INSERT URL FRED - https://iit.aviaryplatform.com/r/0g3gx44z67

•	Watch the video interview conducted in Hebrew in 2003,
o	In the template there are instructions about what you should pay attention to.
o	If you don’t master Hebrew, download the English translation and open it in another window. Document your findings in the table in your template.

**12.b** Different technologies for recording
•	What kind of technology was used to create the original interview with Edith Zierer* in 1946 and the original interview in 2003?
•	How does this relate to the document that you are consulting online? Document your findings in your template.
* If you want to listen to **Edith Zierer**, you have to open the Chrome browser. Click on the small “i” icon and allow Flash Player and pop-ups. Bear in mind that the interview takes a long time to load, so you might want to carry on with another assignment in the meantime.
* 
•	INSERT URL -https://iit.aviaryplatform.com/r/0g3gx44z67

**Comment by frederic-reis** [comment]
Hi Stefania,
It's done in english, french and german.
The first option of the share window was the right one
