### ISSUE TITLE
insert  links from Waybackmachine into text in assignment David Boder 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#153]
Here we are dealing with the following problem. The assignment  1a indicated that you had to go to the website of David Boder and search for specific information. But the website is gone, only the database with interviews has remained. The information that is needed could be traced back in the Wayback machine, but this means that links to 3 different pages have to be included. Would you know how that works? In bold the words in which the link has to be created. 

ASSIGNMENT 
1.a Entering data in a timeline

The chronological sequence of dates needs to be complemented with information. Create an entry in one of the dates in the timeline.

Choose two dates to create entries.
For more background information on Boder besides what is provided in the black box, go to the box “links”, the last section of Boder’s biography, and consult the following resources:
**Voices of the Holocaust.**  (LINKS SHOULD BE ADDED HERE)
https://web.archive.org/web/20200322000230/http://voices.iit.edu/#about
https://web.archive.org/web/20200322000228/http://voices.iit.edu/voices_project 
https://web.archive.org/web/20200322000227/http://voices.iit.edu/project_notes 
Clip 5 min History
Open your template and go to the table for assignment 1a.
Write two entries of max 100 words in the appropriate field.
Look for an appropriate images on the web and copy the links to these images into the same table.
Now cut and paste the entries and the links to the photos and place them in the timeline, following the instructions in the tutorial provided. Remember to regularly save your entries.

**Comment by frederic-reis** [comment]
Hi Stefania,

Could you check ?
I simply add the links below the text in english, french and german.
If you prefer, I can do something like that:  [Voices of the Holocaust](https://web.archive.org/web/20200322000230/http://voices.iit.edu/#about) ([voices project](https://web.archive.org/web/20200322000228/http://voices.iit.edu/voices_project), [project notes](https://web.archive.org/web/20200322000227/http://voices.iit.edu/project_notes))

**Comment by stefaniascagliola** [comment]
hi Fred,


thank you for the fixing, I have closed all the issues,

best

Stefania

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: frederic-reis <notifications@github.com>
Verzonden: zaterdag 19 december 2020 01:42:58
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Author
Onderwerp: Re: [C2DH/ranketwo] insert links from Waybackmachine into text in assignment David Boder (#153)


Hi Stefania,

Could you check ?
I simply add the links below the text in english, french and german.
If you prefer, I can do something like that: Voices of the Holocaust<https://web.archive.org/web/20200322000230/http://voices.iit.edu/#about> (voices project<https://web.archive.org/web/20200322000228/http://voices.iit.edu/voices_project>, project notes<https://web.archive.org/web/20200322000227/http://voices.iit.edu/project_notes>)
