### ISSUE TITLE
web archives as historical sources 1b 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#156]
1.b The difference between the web and the internet

Most people use the terms “web” and “internet” interchangeably as they are very closely linked to each other, even though they are, in fact, two different things. In order to help you understand the crucial differences between the two, watch these two informative and humorous videos:

“What is the world wide web? – Twila Camp” from TED-Ed (2014)(3.50 mins)

- “What is the world wide web? – Twila Camp” from TED-Ed (2014) (https://www.youtube.com/watch?v=J8hzJxb0rpc) (3.50 mins)

https://image.thum.io/get/https://youtu.be/J8hzJxb0rpc

what-web

“The Web Is Not The Net” by VSauce (2014), only from 00:34 to 05:04

After watching these video note the most important differences between the internet and the web.

I have tried with this code, but it made other thumbnails disappear, so I took it away, and the images came back, can you fix this?

- “The Web Is Not The Net” by VSauce (2014) (https://youtu.be/scWj1BMRHUA?t=34), only from 00:34 to 05:04

https://image.thum.io/get/https://youtu.be/scWj1BMRHUA?t=34

web-not-net

-
    title: 'What is the world wide web?'
    slug: what-web
    type: video
    data:
        embed:
            title: internet
            author_name: Twila Camp 
            thumbnail_url: 'https://image.thum.io/get/https://youtu.be/J8hzJxb0rpc'
        year: 2014
    url: 'https://youtu.be/J8hzJxb0rpc'
-
    title: 'The Web is not the Net'
    slug: web-not-net
    type: video
    data:
        embed:
            title: internet
            author_name: VSauce
            thumbnail_url: 'https://image.thum.io/get/https://youtu.be/scWj1BMRHUA?t=34'
        year: 2014
    url: 'https://youtu.be/scWj1BMRHUA?t=34'

**Comment by frederic-reis** [comment]
It's done!  Is ok like that?

**Comment by stefaniascagliola** [comment]
thank. you so much!!!!!
