### ISSUE TITLE
web archives as historical sources 1c

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#157]
1.c The materiality of the internet

Even if we understand the principles, history and evolution of the internet and the web, it can still be hard to fully grasp the materiality of our information systems. Where do we find tangible traces of the internet in our environment and what do they look like? Despite frequent references to “the cloud” and “cyberspace” and the widespread use of WiFi (all of which contribute to the belief that the web and the internet are intangible and transparent), the internet in fact consists of highly tangible elements. For an introduction to how the internet works, watch this TED lecture by Andrew Blum: “What is the Internet, really?” (2012) (https://youtu.be/XE_FPEFpHt4) (12 mins).

card

https://image.thum.io/get/https://youtu.be/XE_FPEFpHt4 

Is this information new to you? How does it compare to what you imagined the internet to be?
What is meant by the line “wired people should know something about wires”? (min. 11.34)
Now take a look at this “Submarine Cable Map 2015” by Telegeography (https://submarine-cable-map-2015.telegeography.com/) The map looks old but it was created in 2015.

**HERE**

Where do you notice the highest and lowest concentration of cables? What does this suggest with regard to power and control in world politics?
Conduct some additional web research and find out how many undersea cables have been built since and now exist in total (don’t forget to cite your source).
--
PLEASE ALSO INCLUDE THE SUBMARINE CABLE MAP THUMBNAIL
https://image.thum.io/get/https://submarine-cable-map-2015.telegeography.com 

--

**Comment by frederic-reis** [comment]
Done!

**Comment by stefaniascagliola** [comment]
merci. beaucoup
