### ISSUE TITLE
WEB archives as historical sources 1d

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#158]
1.d Information systems and power

The placement of underwater cables is not random; it is heavily influenced by history. New communication systems are generally rooted in the infrastructures of previous systems. These developments do not only reflect progress in technology, they are also an expression of power relations. It matters a lot who is connected to whom as well as who pays for and controls information systems. Watch these two videos and then answer the essay question below:

“Thin underwater cables hold the internet. See a map of them all” by Vox (2015)(3 mins)

https://youtu.be/Ve810FHZ1CQ 
https://image.thum.io/get/https://youtu.be/Ve810FHZ1CQ 

card

“Bundled, Buried & Behind Closed Doors” by Ben Mendelsohn (2011) – Vimeo video about 60 Hudson Street and the materiality of the internet (https://vimeo.com/30642376) (10 mins)
https://image.thum.io/get/https://vimeo.com/30642376 

NEW CARD HERE 

Write a short essay of 500 words in which you incorporate the answers to the following questions:

What were the predecessors of the internet cables at the bottom of the ocean?
Why were they laid, for what reason and by whom?
What do you think is the connection with regard to the division of power worldwide between those who had the resources to invest in the system of underwater telegraph cables in the past, and those who at present have taken up this role for fibreglass cables?
Who was the owner of these systems in the 19th century, and who owns the cables that are laid out to connect us with the internet worldwide? What are the implications of this ownership for freedom of information?

PLEASE ALSO ADD “Bundled, Buried & Behind Closed Doors” AS A THUMBNAIL

**Comment by frederic-reis** [comment]
It's done!  I removed the title of the videos in the text to don't have it twice.  
Is it ok like that ?

**Comment by stefaniascagliola** [comment]
muchas gracias
