### ISSUE TITLE
problems with fixed headings in assignments 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#16]
I have gone through all the assignments and there seem to be these problems:

- [x]  ' assignment n. 1 of  ......'  appears , why don't we stick to repeating **Assignment #** as on the earlier screen, the difference does not help the viewer,  and we could also leave it out. 

- [x]  you see 'student' instead of 'briefing student', I tried to change it, but cannot find the place where this text is formulated in GitHub 

- [x]  the structure of the text is a bit chaotic, I tried to set it right, but I miss the possibility to attribute certain features, is an issue of design, 

- [x]  Instead of 'briefing teacher', it says 'challenge teacher', have no idea where that comes from!

**Comment by frederic-reis** [comment]
@stefaniascagliola   Some issues are already checked in the list. That means they are already done ?

**Comment by danieleguido** [comment]
Yes @stefaniascagliola, I've changed the assignment layout as well. Please check the [wiki](https://github.com/C2DH/ranketwo/wiki/Structure-of-assignment) on how to structure an assignment
