### ISSUE TITLE
web archives 2c

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#161]
use the answer form to write down the answers
--

2.c The original ambitions of the Wayback Machine compared to later thoughts

As a historian it is vital to place a resource such as the Wayback Machine in a historical context. Idealism and belief in the democratising power of technology lie at the heart of the creation of this resource. To understand this more clearly, watch these three video segments from a 2011 presentation by Brewster Kahle to the Long Now Foundation (https://archive.org/details/brewsterkahlelongnowfoundation).
https://image.thum.io/get/https://archive.org/details/brewsterkahlelongnowfoundation 

card

The objectives of the Internet Archive as a foundation (9:36 - 12:30)
How the Wayback Machine is used to preserve the web (40:55 - 44:39)
The preservation strategies pursued by the Internet Archive and the Wayback Machine (45:41 - 50:20)
Now answer the following questions (with additional web research if needed):

What was the Library of Alexandria?
How would you describe Brewster Kahle’s idea of “universal access to all knowledge” in your own words?
What is the value of preserving web pages for a historian?
Why are there multiple physical locations for the digital archives of the Internet Archive?

Now compare the narrative in the passages you watched from 2011 with the discourse adopted in the opening keynote talk by Brewster Kahle in 2019 at the Charleston Conference (https://youtu.be/bA67X9y-ozc from 3:29 to 12:22)

https://image.thum.io/get/https://youtu.be/bA67X9y-ozc 

card

and answer the following questions:

What strikes you as different?
In your opinion, why might Kahle’s idea have changed?
Do you think this collaboration with Wikipedia is a good direction for the Internet Archive and the Wayback Machine to go in? Why or why not?

**Comment by frederic-reis** [comment]
It's done!

**Comment by stefaniascagliola** [comment]
grazie mille!
