### ISSUE TITLE
WEB ARCHIVES 3A

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#162]
3.a Challenges and limits of preservation: The example of the Luxembourg Web Archive

In this sub-assignment, the Luxembourg Web Archive (LWA) (https://www.webarchive.lu/) managed by the BnL will be explored to identify the benefits, limitations and challenges of web archiving. Web archivists have the task of defining the parameters and criteria for their digital collection of web pages. They have to decide which types of sites they should archive (i.e. government sites, news agency sites, museum sites, personal blogs, etc.), how many times a year snapshots should be taken, and how this content can be made accessible to their audience.

Imagine that you work at the National Library of Luxembourg and your job is to help select and collect all the relevant information on the web that pertains to the Grand Duchy of Luxembourg. Now imagine that a secondary school student wants to understand how the LWA works and has asked you to help explain it to her. Using the information found on the main page of the Luxembourg Web Archive (https://www.webarchive.lu/), its FAQ section (https://www.webarchive.lu/faq/) and the “How it Works” page (https://www.webarchive.lu/how-it-works/), answer the following questions that are posed by this imaginary secondary school student:

I would like to add this image in this assignment:

https://image.thum.io/get/https://www.webarchive.lu/how-it-works/ 

**THUMBNAIL HERE** 

Regarding the collection policy of the LWA, who or what are Luxembourgish publishers?
How many times a year do you (the BnL) archive the Luxembourgish web?
Which types of websites do you archive (e.g. government sites, news agency sites, personal blogs, etc.)?
How can someone access the information in the LWA?
What is your process for collecting information for the LWA? (Hint: it’s a three-step process)
What are the three different types of crawls used by the LWA and what are the differences between them?
What are some of the reasons that you might decide not to collect a website?

**Comment by frederic-reis** [comment]
It's done!
I can change the size of the image if you which.

**Comment by stefaniascagliola** [comment]
choucra
