### ISSUE TITLE
web as historical source  4 out of 5  - add giff about Europe after first text block 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#165]
4 out of 5 — The policy of an international institution: How the European Union preserves its web archives ¶

The act of archiving is not just driven by neutral concerns for preservation. It is very much embedded in ways of prolonging and solidifying one’s identity, status and position. According to Janne Nielsen, who proposes a clear distinction between “macro” and “micro” archiving (http://www.netlab.dk/wp-content/uploads/2016/10/Nielsen_Using_Web_Archives_in_Research.pdf), it is important to differentiate, for example, between a powerful institution that designs a preservation strategy for prosperity with a broad imaginary future audience in mind (“macro”) and a scholar at the end of a funded project who manages to conserve her data for future use within her academic career (“micro”). In the case of the EU, as the examples below show, preservation is also relevant for reasons of transparency about how decisions are taken or how legal frameworks intended to protect citizens and their cultural heritage evolve over time. The case study presented here – how the European Union deals with the preservation of its web archives – is an example of macro-archiving. The “level” of archiving in this context should be kept in mind throughout the example.

I would like to add this giff
https://media.giphy.com/media/B22vnwkQSMldC/giphy.gif 
**HERE**

**Comment by frederic-reis** [comment]
It's done. Is it ok like that ?
I also enabled all links and setup to open in a new tab.

**Comment by stefaniascagliola** [comment]
spasiba

**Comment by frederic-reis** [comment]
Pozhaluysta
