### ISSUE TITLE
web as historical source - 4 a - add thumbnails of 2 european institutions 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#166]
There are two ways of consulting the web archives of the EU. You can use the Internet Archive’s Wayback Machine (https://archive.org/web/), which has taken random snapshots since the very beginning of the web in 1996 on a non-profit basis, or you can consult the European Union Web Archive (https://www.archive-it.org/collections/12090), which consists of web pages that are covered more systematically by the Internet Archive’s paid service, Archive-It, which started to offer these services in 2006. The institution responsible for preservation policy is the Publications Office of the European Union. Based in Luxembourg, this inter-institutional organisation has the task of producing and disseminating the EU’s publications, providing free access to official information and data from the EU, and ensuring the long-term preservation of content produced by EU institutions and bodies. For this assignment we will use the Wayback Machine and our corresponding “cheat sheet” to compare the archived content of two EU agencies over time: the European Court of Justice (https://curia.europa.eu/) and the European Institute for Gender Equality (https://eige.europa.eu/).

● Tip: The best way to compare the two is to take a screenshot of each home page, decrease the size, and then place them next to each other on your screen.

**HERE NEXT TO EACH OTHER THUMBNAIL OF CURIA** 
https://image.thum.io/get/https://curia.europa.eu/ 
**THUMBNAIL OF EIGE** 
https://image.thum.io/get/https://eige.europa.eu/ 

Open the Internet Archive’s Wayback Machine (https://archive.org/web/) in two different tabs. In the first tab, search for the snapshots of the European Court of Justice (ECJ) using the URL of its home page: https://curia.europa.eu/. In the second tab, search for the snapshots of the European Institute for Gender Equality (EIGE) using the URL of its home page: https://eige.europa.eu/. Then, using the web archives and any additional web research needed, complete the table below:

**Comment by frederic-reis** [comment]
It's done!

**Comment by stefaniascagliola** [comment]
obligado
