### ISSUE TITLE
Depublish medieval lesson

### ISSUE THREAD

**Issue by spapastamkou** [C2DH/ranketwo#186]
The lesson ["The Chronicle of Dalimil: a photogenic mediaeval manuscript?"](https://ranke2.uni.lu/u/manuscript/) has since long been advertised as "upcoming". An essentially unifinished version was published online (S format) but no additional pedagogical material was in the pipeline. The video clip will be depublished as the decision was taken to not go forward with this lesson.

**Comment by spapastamkou** [comment]
Starting a list with files of this lesson. 
`https://github.com/C2DH/ranketwo/tree/master/_units/manuscript`
`https://github.com/C2DH/ranketwo/tree/master/assets/videos/rare-manuscript`

@danieleguido @frederic-reis Do we agree that to depublish this lesson, I only have to remove these files? Please let me know if I need to do other changes as well (I checked all folders but did not find related files). Thanks a lot!

**Comment by frederic-reis** [comment]
Hi @spapastamkou,
Not the rare-manuscript video. It's a video integrated inside the clip on the home page.
You can remove:
* `/_units/manuscript` folder.
* The 3 `manuscript.md` file in the _units folder
* All the manuscript entries in the _data/iframes.yaml file

**Comment by spapastamkou** [comment]
@frederic-reis j'ai oublié l'essentiel, koi:-) Merci beacoup!

**Comment by spapastamkou** [comment]
@danieleguido There is one more thing to note here: that the clip still remains available on Vimeo. I have no access there - I believe it is you and Noëlle? - but I am not sure I need to, at least for now! In any case, there is no reason in my view to depublish the video from there, as the main problem is less the clip and more the fact that it is orphan from further contact. Let me know if you think otherwise, in which case we see how we do. Thanks!

**Comment by spapastamkou** [comment]
@danieleguido One more thing on this - there will be no more, I promise:-) As there was a quiz as well, there is stuff remaining on Playposit. Have no access there either. Just drop this here to discuss it outside GH, as it does not affect this issue which will close after the merge.
