### ISSUE TITLE
Depublish L format of Archival to digital lesson

### ISSUE THREAD

**Issue by spapastamkou** [C2DH/ranketwo#188]
Depublish the large format of the Archival to digital lesson.

**Comment by spapastamkou** [comment]
Liste des fichiers afférents: 
- [ ] `/_units/archival-digital-turn/workshop.en.md` + `large.de.md`, `large.fr.md`
- [ ] `/assets/images/archival-digital-turn/workshop.jpg`
- [ ] `_workshops/archival-digital`- all subfolder
- [ ] `assets/pdf/archival-digital-turn`- all subfolder
- [ ] `assets/Digital Source Criticism Winter School 2017.pdf`

**Comment by spapastamkou** [comment]
@frederic-reis Merci de jeter un oeil à la liste ci-dessus pour voir si quelque chose m'échappe? 
Aussi, le tout dernier fichier de la liste, un PDF directement rattaché à assets, je le vois dans l'arborescence mais ne l'ai pas rencontré sur le site. Son nommage diffère aussi des autres et se départit de la règle, saurais-tu de quoi il s'agit et s'il faut y toucher ou pas?

**Comment by frederic-reis** [comment]
Oui c'est bon.
Pour le dernier pdf, je pense pas que c'est lié au workshop.
Je me demande si c'était pas prévu d'avoir un lien sur cette page vers le pdf mais que ça n'a jamais été fait: https://github.com/C2DH/ranketwo/blob/master/pages/define-dsc-skilltraining.md

**Comment by spapastamkou** [comment]
Merci @frederic-reis . Je vais pas toucher à ce pdf errant pour le moment par précaution, surtout qu'il gêne personne...

**Comment by spapastamkou** [comment]
Closed by #199.
