### ISSUE TITLE
download assignments in PDF with logo of CdDH

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#21]
The concept of the teaching structure, is that the assignments are downloadable, and that they can be used by lecturers in another environment (Moodle, Canvas, Blackboard). But we don't want people to mess around with our content, so we need a kind of Marker on each of the assignments of the C2DH and of Uni Lux, how can we arrange this?

**Comment by frederic-reis** [comment]
@danieleguido  I've updated the style of the template and committed changes

**Comment by danieleguido** [comment]
thanks @frederic-reis I have merged into master ;)
