### ISSUE TITLE
bullet lines in assignments

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#22]
where do I find the possibility to add bullet lines to actions that students have to take? 

- Stop the clip when the poster is shown and take a print screen. As the text is in Hebrew, you are going to use Google’s image recognition technology to find more information about the poster. 
- go to Google Image, click on the icon of the photo camera in the search bar, choose  ‘upload’ and upload the print screen of the poster.
You will find references to a collection of Jewish posters 
- Write a short abstract of max 150 words about this collection, based on applying source criticism to its website:
                     -  Who created the organisation? 
                     -   Who created the website?

**Comment by frederic-reis** [comment]
You can use this markdown syntax:

* bullet level 1
  * bullet level 2
  * bullet level 2
* bullet level 1
