### ISSUE TITLE
add ISSN in footer

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ranketwo#225]
- one ISSN per lanaguage
- add ISSNs in cofig yml

**Comment by spapastamkou** [comment]
We do this manually via the footer file; add all three issn numbers on page(s) d'accueil - @danieleguido 
I close this issue.

**Comment by spapastamkou** [comment]
I just dropped a note on the commit, but drop here as well: the ISSN numbers are not visible on the live website currently:)
