### ISSUE TITLE
what is the syntax for hyphen - ?

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#24]
Hi Fred, 

I have gone through many of my issues with Daniele, but there are some that have not been solved.
One of them is the use of 'hyphen' -    , I think it makes sense to only give numbers to the entire assignment, en add letters to the subcategory of assignments,  elements of the assignments, and when it comes down to instructions: do this, write this, to use hyphens - , but I can't find the syntax for hyphens that you sent me. I use it in markdown, but it does not show on the website, you only see numbers, so there must be something wrong with how I wrote it. 

see:

a. Create an entry in one of the dates in the timeline
The chronological sequence of dates needs to be complemented with information.
Choose two dates to create an entry. For more background information on Boder besides what is provided in the black box, you can click on ‘links’, the last section of Boder’s biography, and consult the following resources:

1. Voices of the Holocaust
2. Clip 5 min History.

- Open your template and go to the table for assignment 1a
- Write 2 entries of max 100 words in the appropiate field.
- Look for an appropriate image on the web and copy the links to these images in the same field Now cut and paste the entries and the links to the photos and place them in the timeline (if it is not clear how to proceed, read the tutorial) Remember to regularly save your entries in your answer template, as well as in the online timeline!

**Comment by frederic-reis** [comment]
@stefaniascagliola  Could you put the link to the page ?

**Comment by frederic-reis** [comment]
I've updated the css to respect the markdown syntax. It should be better now.
