### ISSUE TITLE
check assignment documentation in wiki

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ranketwo#27]
Hello, I put a short documentation about the structure of an assignment: https://github.com/C2DH/ranketwo/wiki/Structure-of-assignment

**Comment by danieleguido** [comment]
@stefaniascagliola is it ok to close the issue?

**Comment by stefaniascagliola** [comment]
looks great, thank you!!! will be very helpful

S.

Dr. Stefania Scagliola
post doc researcher
project: teaching platform for digital source criticism

University of Luxemburg
Luxemburg Centre for Contemporary and Digital History/C2DH
Maison des Sciences Humaines
11, Porte des Sciences / L-4366 Esch-Belval
Office: 4.141
tel: + 352-466644 - 9406 / mobile: + 31-621467752
e-mail: stefania.scagliola@uni.lu






________________________________
Van: Daniele Guido <notifications@github.com>
Verzonden: woensdag 12 september 2018 11:29:31
Aan: C2DH/ranketwo
CC: Stefania SCAGLIOLA; Mention
Onderwerp: Re: [C2DH/ranketwo] check assignment documentation in wiki (#27)


@stefaniascagliola<https://github.com/stefaniascagliola> is it ok to close the issue?
