### ISSUE TITLE
go to assignment button does not display in FR and DE pages of lessons

### ISSUE THREAD

**Issue by spapastamkou** [C2DH/ranketwo#270]
The "go to assignment" button under the title and abstract of a lesson does not display in French and in German in the FR and DE lesson pages of the website (I provide an [example link](https://ranke2.uni.lu/de/u/archival-digital-turn/)). It is in English, although the translation is provided in the `_data/i18n.yaml`. I believe there is somewhere a script to edit, so I open this issue to document the need. 

Cf. the screenshot with the problem - also note here that the button is not very visible there. 

![go-to-assignments-button-goes-multilingual](https://github.com/C2DH/ranketwo/assets/27706167/b0ebbfe6-1a88-46b9-961b-c85447760fa6)

**Comment by spapastamkou** [comment]
@danieleguido we can perhaps see this briefly next Friday when we meet - or if @frederic-reis you have time in the meantime, let us know if you have an idea how and where to fix this and we might work on it with Artur. Thanks!

**Comment by frederic-reis** [comment]
Comme je m'en doutais, c'est parce que la clef dans le fichier _data/i18n.yaml ne correspond pas à la clef dans le fichier _layouts/unit.html (ligne 50)

**Comment by spapastamkou** [comment]
I cc @arturamiryan to introduce him smoothly here :-) No need to do anything more for the moment though. 

Thanks a lot @frederic-reis - je reviendrai:)

**Comment by spapastamkou** [comment]
fix in PR #273
