### ISSUE TITLE
documents from Google doc to our server?

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#28]
Hi Fred and Daniele,

In his review Gerben pointed out that all documents to which we now refer in the assignments ( guide to how to use timelines, checklist for reliability website etc) and are now placed in a Google folder, should be transferred to our server somewhere, would you know how to deal with this and what do you need from me to arrange this? 
When we have our central review on the 5th, I would like to address the request, 
best

Stefania

**Comment by danieleguido** [comment]
Hi @gerbenzaagsma and @stefaniascagliola 
each line in the google spreadsheet is automatically integrated in [_data/documents.yaml](https://github.com/C2DH/ranketwo/blob/master/_data/documents.yaml). The [nodejs script](https://github.com/C2DH/ranketwo/blob/master/scripts/documents.js) included in this repo takes care of the import. To display the document (e.g. an image) in a text, simply 

- get the slug from the table, e.g. `delalande-vincent-historien-cyborg`
- add the slug to the `documents` list in components, units and assignment markdown files (in yaml front matter)

If you want to add a reference inside the markdown text, is as easy as adding a **markdown link** using specific text:

- `[cit](delalande-vincent-historien-cyborg)` will be rendered as: `(Nicolas Delalande, Julien Vincent, 2011)` in the html page, linked to the external url specified in the table, in this case [(Nicolas Delalande, Julien Vincent, 2011)](https://www.cairn.info/revue-d-histoire-moderne-et-contemporaine-2011-5-page-5.htm)

- `[ref](delalande-vincent-historien-cyborg)` will be rendered as simple inline reference: Nicolas Delalande, Julien Vincent, *Portrait de l''historien-ne en cyborg*, 2011 [(link)](https://www.cairn.info/revue-d-histoire-moderne-et-contemporaine-2011-5-page-5.htm)

- `[card](delalande-vincent-historien-cyborg)` will be rendered as a **block element** containing the **thumbnail** and a few metadata in a form of a ["bootstrap card"](https://getbootstrap.com/docs/4.0/components/card/). This option should be used only when we have a thumbnail for that.

Links with other text will work as usually, we just change the url behind.
There are other possible options, but they won't be covered for the moment.

If it doesn't work in your text, please **create a specific issue** with the **page url** and the code you have used to created it.
