### ISSUE TITLE
display "table of contents" in German and French

### ISSUE THREAD

**Issue by spapastamkou** [C2DH/ranketwo#294]
In all lessons in every language of the website, "table of contents" (the term) displays in English. It should display in French and in German in respective languages. 
- table de matières - FR
- [German term] - DE

**Comment by spapastamkou** [comment]
I did not find this in data, need some help @frederic-reis !

**Comment by frederic-reis** [comment]
J'ai trouvé. Ligne 204 dans `_layouts/unit.html`

![image](https://github.com/C2DH/ranketwo/assets/40597434/a8d0eb32-4bbb-458b-9ad5-1e0ec5b5409c)

La clé est table of contents.
Il suffit d'ajouter une entré dans `_data/i18n.yaml` pour table of contents

**Comment by spapastamkou** [comment]
thanks, it works in the preview, so I will merge now.
