### ISSUE TITLE
How to define Digital Source Criticism?

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#30]
For this page, I have to rewrite the text in ways that paragraphs or boxes are created, and there has to be some place for images, it is too much text, Daniele can you suggest a format? What about a background image, a kind of structure that resembles what we do with home, 
fingers (digit) , a water source (source), and a magnifying glass????(criticism)

**Comment by danieleguido** [comment]
I close this issue for simplicity sake, ref issue #31 on page layout. 
it will behave as a "normal" page for now, not sure there's enough time to design a new format.

**Comment by stefaniascagliola** [comment]
ok, then only more white space between the paragraphs, 
S
