### ISSUE TITLE
fix assignment "teacher section" in both layout and contents

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#32]
looks beautiful! So actually this is not an issue ;;;)))) 

In Boder's lesson, the long text besides the interactive is a bit of a problem, 
In Assignments, the left side looks fine, the right side is too close to the earlier and following assignment, it blurs, hardly any distinction, more space, 

S.

**Comment by danieleguido** [comment]
Hello @stefaniascagliola 
grazie 💃 

I've seen the long text, but probably we can shorten it, all those the instruction are really necessary?
For the spacing, there is still no styling on assignments divs. @frederic-reis, can you do that?

**Comment by stefaniascagliola** [comment]
will edit text to shorten it, will do that any way, everything is too long !!

**Comment by danieleguido** [comment]
Component contents issue: https://github.com/C2DH/ranketwo/projects/1
