### ISSUE TITLE
fix "transformations" unit

### ISSUE THREAD

**Issue by danieleguido** [C2DH/ranketwo#36]
Hi @stefaniascagliola, 
the current playposit url leads to a login wall. 
Please:

- [x] add the correct url for the **embed** in the [_data/iframes.yaml](https://github.com/C2DH/ranketwo/blob/master/_data/iframes.yaml) table, as a value for the property `src`
- [x] then review /rewrite the text in the [quiz component](https://github.com/C2DH/ranketwo/blob/master/_units/transformation/quiz.en.md)

**Comment by stefaniascagliola** [comment]
Done! The settings in the quiz were not set to SHARE!

**Comment by danieleguido** [comment]
Perfect, I can close the issue. Feel free to reopen if needed
