### ISSUE TITLE
change Learing into Learning in assignments text 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#41]
could you change this?
S.

**Comment by danieleguido** [comment]
@stefaniascagliola you mean the title of the page? Can you include the url and a screenshot?

**Comment by stefaniascagliola** [comment]
no I mean the spelling mistake, in the left column of the assignments lay out 

<img width="272" alt="screen shot 2018-08-13 at 18 59 47" src="https://user-images.githubusercontent.com/33933280/44046449-c4daa68c-9f2b-11e8-9073-a6fb82498473.png">
<img width="272" alt="screen shot 2018-08-13 at 18 59 47" src="https://user-images.githubusercontent.com/33933280/44046472-d66a5f50-9f2b-11e8-8fd0-1773d216ef9c.png">

https://c2dh.github.io/ranketwo/u/boder/

**Comment by stefaniascagliola** [comment]
sorry, you already replaced it, I was viewing an old version of the page!!!
S.
