### ISSUE TITLE
texts of assignment 2 and 9 are duplicated at the right side 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#49]
Dear Fred, 

Have solved the main issues, but in assignment 2 and 9 the text of the assignment appears again in the right side, which should not, can you let me know why and how I can take it away?
best
Stefania

**Comment by frederic-reis** [comment]
It's fixed !

**Comment by stefaniascagliola** [comment]
thank you!!!!!!

**Comment by frederic-reis** [comment]
`<!-- briefing-teacher -->` was missing
