### ISSUE TITLE
the need to again create French and German assignment 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#50]
Dear Fred,

I just found out, that all the corrections in the texts, such as substituting 'click here' with the description of the website, the correction of the numbers of the assignments, and all other small things,  that I changed in the English files, have not been automatically integrated in the French and German file. This means that I either have to to everything again in the Fr and Ger files, or we could wait until I have finalised everything, and again create Fr and Ger files. 
What do you think of this approach?
Could you to that for me or do we need Daniele?
best
Stefania

**Comment by frederic-reis** [comment]
Hi Stefania,

I think it's better to wait to finalize all before creating fr and de files
