### ISSUE TITLE
new I-frames for quizzes

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#51]
Dear Fred,

I have tries to change the settings of the Quizzes clips, because they now require a login, which should not be the case. But I see that in the I-frames list, there are some annotations for the clips with brackets "..." 

Boder   src: "https://app.playposit.com/share/258439/797374/David-Boders-Interview-collection" 

and some without, Archival to Digital Turn, 
src: https://www.playposit.com/play/823197/from-archival-to-digital-turn 

so I doubt whether to keep the brackets or take them away,  what is the proper annotation?

greetings
Stef

**Comment by frederic-reis** [comment]
Hi Stefania,

You can use or not quotes in yaml files but quotes are required for some special characters :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, `

So, to avoid issues, I recommend to use quotes for text and url. For others properties like id, type, etc., you don't need to use it

**Comment by stefaniascagliola** [comment]
could you now check whether you can enter the quiz of Boder, the quiz of Transformation and the quiz of from Archival to Digital turn without having to log in? I can't check, because it immediately recognises my IP and my password appears, all the other persons who have used my passwords, have the same problem,

**Comment by frederic-reis** [comment]
I've just cheked and the 3 quiz work without having to log in.
There is just an issue with Boder. The quiz is duplicated.

**Comment by frederic-reis** [comment]
I fixed the issue with the duplicate quiz
