### ISSUE TITLE
table in assignments 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#53]
Hi Fred, 

could you sort out how I can show a table in the assignments? 
I need to integrate a table with the information below, in one of the assignments, but don't know how, 
Could you create the source code for a table and put it in assignment 5 about digitised newspapers, in the lesson From Archival to Digital Turn? If you put it there, I am sure I can complete it with out accidentally changing anything which could again lead to an error. 

best
Stefania

  | 1. Institution | 2. Type of access | 3. Interface | 4. Collection specificities
-- | -- | -- | -- | --
Europeana newspapers (multilingual) |   |   |   |  
E-Newspapers CH (FR+DE) |   |   |   |  
Gallica (FR) |   |   |   |  
Retronews (FR) |   |   |   |  
ProQuest (EN) |   |   |   |  
Chronicling America (EN) |   |   |   |  
Delpher (NL) |   |   |   |  
ANNO (DE) |   |   |   |  
Zeitungsportal DDR-Presse (DE) |   |   |   |

**Comment by frederic-reis** [comment]
It's not the assignment 6 ?
Where exactly 6a, 6b ?

**Comment by stefaniascagliola** [comment]
it is 6a, and I need it  after this text:

- What type of institution carried out the digitisation? public/private, for commercial/academic/preservation purpose?
- How to access these collections? Is a subscription needed?
- Is there a dedicated interface for the digitised newspapers or is the interface common to other sources, such as books, images?
- What is specific to that collection? 
- Where do the titles come from? 
- Which languages are available? 
- Are there some special sub-collections?

**Comment by frederic-reis** [comment]
It's done!

**Comment by frederic-reis** [comment]
Is it ok like that ?

**Comment by stefaniascagliola** [comment]
Dear Fred, 

I am sorry, I think I have messed up your work, I added links to the newspaper website, and probably unintended deleted the code that you had put it to create a table. Could you have a look at it again. I hope that some day I will learn to be more precise ;;;;))))))
best
Stefania

**Comment by frederic-reis** [comment]
I put the table again. I don't know if it's at the right place.
