### ISSUE TITLE
adding authors Juliane and Florentina does not work

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#56]
I have tried to copy the procedure created to add authors, 
have created mark down file, have added their names and urls in the folder Authors, 
the reference there should be to their 'slug' in the google table, but I can't find the already integrated authors Max Kemman, and Estelle Bunout/Marten During in the Google table with the tab with authors, only my name and Daniele's name, can't find it in other tabs, where have these slugs been put? Maybe in another Google doc? 

https://docs.google.com/spreadsheets/d/1kRGo8pfsXjugWRRM3H5T2Ew-sHtGiqDPH0grV74y5MA/edit#gid=213209822 

Fred, could you help me out?

**Comment by danieleguido** [comment]
metadata field is `authors`
