### ISSUE TITLE
change moving titles 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#57]
Hi Fred or Daniele, 

Do you know  where I can find these sentences:

Ranke.2 is a teaching platform etc. etc

 I would like to change the parts that are static and dynamic 

if you think this is risky, then please go ahead and change it for me: 

Ranke.2 is a Teaching Platform  (fixed) 
-- on Digital Source Criticism (dynamic)
-- on how to critically assess historical digital sources (dynamic)
-- on different types of data (dynamic)
-- on how analogue sources are turned into digital representations (dynamic)

**Comment by danieleguido** [comment]
Change the metadata in `pages/index.md`
```yaml
sentences:
- Ranke.2 is a Teaching Platform  on Digital Source Criticism
- Ranke.2 is a Teaching Platform  on how to critically assess historical digital sources
- Ranke.2 is a Teaching Platform  on different types of data
- Ranke.2 is a Teaching Platform  on how analogue sources are turned into digital representations
```

**Comment by stefaniascagliola** [comment]
I have changed the titles in https://github.com/C2DH/ranketwo/edit/master/pages/index.md, but it has not changed on the website, should something more be added?
Stefania

**Comment by stefaniascagliola** [comment]
Hi Frederic, thanks looks great, but could you  also include 'on' in the dynamic part? The idea is that 
'Ranke is a teaching platform' is the fixed part, 
thanks, 
Stefania

**Comment by frederic-reis** [comment]
It's done !
