### ISSUE TITLE
add a pdf

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#58]
Dear guys, 

sorry, my brain is a sieve,  can you again list the steps to add a link to the pdf in GitHub?
I have uploaded it ih the folder PDFs in assets, and want to create a link to it in an assignment, 
tried to look at the example that is in there, the timeline assessment, but it is still linking to the google drive, not to the gitub folder, 
do I create a meta-data field in the assignment with - document: and then add slug?
but which slug do I add in the document that I have created?

**Comment by danieleguido** [comment]
The pdf will be visible under `https://ranketwo.uni.lu/assets/pdf/ ... ` @stefaniascagliola you can use this absolute link
