### ISSUE TITLE
Replace the title "genealogy of the term Digital Source Criticism"

### ISSUE THREAD

**Issue by frederic-reis** [C2DH/ranketwo#6]
Replace by "How to define Digital Source Criticism?"

**Comment by frederic-reis** [comment]
@stefaniascagliola  I changed the title. Could you check if it's ok : https://c2dh.github.io/ranketwo/genealogy/

Would you like I also change the url of the page ?

**Comment by stefaniascagliola** [comment]
Hoera!!!!! Great!!!!
Stefania

**Comment by frederic-reis** [comment]
Would you like I also change the url of the page ?

**Comment by stefaniascagliola** [comment]
Yes please!!! So there is consistency and I don’t get confused!
S.

**Comment by frederic-reis** [comment]
I changed the url. Could you check ?
If it's ok, you can close the issue.
