### ISSUE TITLE
open link in new tab 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#61]
Dear Fred, 

in the review of the assignments a student suggested that  opening the links in the assignments in a new tab,  would create more coherence in the way the students can consult and switch from the assignment to the link. This is natural for anybody with some digital skills, but not for young students. 
I imagine this is not something we can already incorporate in the links?  Shall I then suggest it in each assignment? 
best
Stefania

**Comment by frederic-reis** [comment]
Hi Stefania,

You mean for external links ?  It's doable. I can incorporate that directly in the link.

**Comment by frederic-reis** [comment]
Stefania,

To force a link to open in a new tab, you need to add `{:target="_blank"}` at the end of the Markdown syntax.  

Ex: `[this interview with Janis B.](http://voices.iit.edu/audio.php?doc=bJanis){:target="_blank"}`
