### ISSUE TITLE
integrate French and German text of Boder assignments 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#64]
dear Fred, 

Could you integrate the translation of the assignments on Boder in French and German? 
See the attachments. They are not in plain text, but integrated in the template that I had prepared in Google doc, before Daniele changed the structure of the assignments. 
I think it may be hard, I would like you to first try with French, which you master, I think the best way to work, is have the English version of the assignment on one screen in GitHub and work on the other language on another screen. I will be arriving this evening in Belval, and am at your disposal these coming 2, 5 weeks until the launch on the 25th, 

best
Stefania 

[2018.09.19 Review Assignments Boder_R_FR (vf).docx](https://github.com/C2DH/ranketwo/files/2455205/2018.09.19.Review.Assignments.Boder_R_FR.vf.docx)
[2018.09.19 Review Assignments Boder_R_DE (vf).docx](https://github.com/C2DH/ranketwo/files/2455206/2018.09.19.Review.Assignments.Boder_R_DE.vf.docx)

**Comment by frederic-reis** [comment]
Hi Stefania,

I started with the first assignment in fr and de until the point 1c. I kept the english structure but I think there're still some issues in the look and feel of the english version.
I also noticed that there is a few text which are not translated.

I also noticed another issue: In the instruction section of the english version, the link https://allthingsmoving.com/DBinteractive/#Index doesn't work. But the link for the french and english version in the attached documents works well  https://allthingsmoving.com/DB_interactive_2018_07_03/#Intro. Do you wish I use this one in the english version ?

best

Fred

**Comment by frederic-reis** [comment]
* [ ] Assignment 1 (See #67 for issues)
* [ ] Assignment 2
* [ ] Assignment 3
* [ ] Assignment 4
* [ ] Assignment 6
* [ ] Assignment 7
* [ ] Assignment 8
* [ ] Assignment 9
* [ ] Assignment 10
* [ ] Assignment 11
* [ ] Assignment 12

**Comment by frederic-reis** [comment]
I need the german translation for "1 **out of** 12"

**Comment by stefaniascagliola** [comment]
do you mean literally: "1 out of 12" or do you need the text of assignment 1?

I will check with Maria Cristina tomorrow morning, 
Stefania

**Comment by frederic-reis** [comment]
Only the term "out of"

**Comment by stefaniascagliola** [comment]
Hi Fred,

just checked with Maria Cristina:

I need the german translation for "1 out of 12"

1 von 12    for German
1 sur  12    for French

**Comment by frederic-reis** [comment]
It's done!
