### ISSUE TITLE
short references to lit in passages tab Introduction - 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#76]
How can I create short references (Owens, 2017) instead of: Trevor Owens, The Evidentiary Basis of Digital History in Companion to Digital History., 2017
→ (Trevor Owens , 2017)
https://github.com/C2DH/ranketwo/blob/master/pages/introduction.md

**Comment by danieleguido** [comment]
Hi @stefaniascagliola, (as a quick memo) 
added the `lit` option along with `ref` and `card` for *documents links*
[lit](owens-digital-sources-digital-archives)
