### ISSUE TITLE
About the project into complete the assignments 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#8]
Can you change 'About the project'  into 'complete these assignments' this is in the Tab teaching modules Boder, next to  'introduction and assignments'

**Comment by frederic-reis** [comment]
I fixed the problem you had when you tried to change the text in the i18n.yaml file.
You should now be able to change the text without impacting the navigation.

**Comment by frederic-reis** [comment]
As discussed, I changed the title to "about the lessons" and I move the whole block to the top of the page
