### ISSUE TITLE
Insert French and German translations assignments RANKE 1 to 7

### ISSUE THREAD

**Issue by frederic-reis** [C2DH/ranketwo#87]
[2018.10.22 Assignment 1_3 archival to digital turnR_DE (vf).docx](https://github.com/C2DH/ranketwo/files/2505234/2018.10.22.Assignment.1_3.archival.to.digital.turnR_DE.vf.docx)

[2018.10.22 Assignment 1_3 archival to digital turn_R_FR (vf).docx](https://github.com/C2DH/ranketwo/files/2505236/2018.10.22.Assignment.1_3.archival.to.digital.turn_R_FR.vf.docx)

**Comment by frederic-reis** [comment]
List of issues (@stefaniascagliola):

* [ ] **All assignments (fr, de)**: need translation for assignment titles and learning outcomes
* [ ] **1a (fr, de)**: the text of this section has changed in english. Need a new translation. 
* [ ] **1b (fr, de)**: it misses translation for `Commentaire sous une vidéo YouTube from ferociousgumby (you don’t have to watch the whole video)` and `you only have to watch the first minute of each video`
* [ ] **3. Instructions**: Is the link correct ? 
* [ ] **3b (fr, en, de)**: it misses the url for the link of the by Ralph Pugharti

**Comment by frederic-reis** [comment]
[2018.10.23 SS_Ranke Assignments 4 to 7_R_FR (vf).docx](https://github.com/C2DH/ranketwo/files/2562411/2018.10.23.SS_Ranke.Assignments.4.to.7_R_FR.vf.docx)

[2018.10.24 SS_Ranke Assignments 4 to 7_R_DE (vf).docx](https://github.com/C2DH/ranketwo/files/2562413/2018.10.24.SS_Ranke.Assignments.4.to.7_R_DE.vf.docx)

**Comment by stefaniascagliola** [comment]
Hi Fred, do you want me to do something?
best
Stefania

**Comment by frederic-reis** [comment]
No, it's just for me. :)

**Comment by frederic-reis** [comment]
Hi @stefaniascagliola,

I finished to insert french and german translations for the "From the archival to the digital turn" lesson.

Here is the list of issues I noticed.

* [ ] **All assignments (fr, de)**: need translation for learning outcomes
* [ ] **Assignments 1 to 4 (fr, de)**: need translation for assignment titles
* [ ] **Assignments 4 to 7 (fr, de)**: need translation for "In collaboration with:"
* [ ] **1a (fr, de)**: the text of this section has changed in english. Need a new translation. 
* [ ] **1b (fr, de)**: it misses translation for `from ferociousgumby` in the sentence `Commentaire sous une vidéo YouTube from ferociousgumby`.
*  [x] **3. Instructions**: Is the link correct ? 
* [x] **3b (fr, en, de)**: it misses the url for the link of the article by Ralph Pugh. The url must be set in the Google Sheet.
* [ ] **6. Instructions (fr, de)**: Need the pdf  "interface eluxembourgensia" in french and german (The translation is in the `2018.10.23 SS_Ranke Assignments 4 to 7_R_FR (vf)docx` file)
* [ ] **6 Reading/Viewing suggestions (en, fr, de)**: no content
* [ ] **7. Instructions (en, fr, de)**: The url to Google Image explanation is missing
* [ ] **7. Instructions (fr, de)**: Need the pdf "What works and what doesnot" in french and german (The translation is in the `2018.10.23 SS_Ranke Assignments 4 to 7_R_FR (vf)docx` file)
* [ ] **Workshop (fr, de)**: To translate
