### ISSUE TITLE
change links in Defining Digital Source Criticism in Ger and Fr

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#89]
I want to change the sentences with links in page Digital Source Criticism 

Phd Skill Training, 30/31-10-2017: Exploring the origin and use of the term Digital Source Criticism 
[blok]

Expert Meeting, 18-12-2017 : Various Perspectives on the concept of Digital Source Criticism
[blok]

into fr and ger sentences, but can't find the place where to change this 

can Fred or Daniele help out?

S.

**Comment by stefaniascagliola** [comment]
have found the location in documents website Ranke - google sheets - 
created:


dsc-skill-training-de
dsc-skill-training-fr
quelle-de
quelle-fr

with Fr and Ger sentence, 
have put this aside [blok] in brackets (. )

I believe Fred has to 'pull' something, to make these sentences appear in Define De and Define Fr. 

is this correct?

best
Stefania

**Comment by frederic-reis** [comment]
It was almost good. It missed some info in the Google Sheet.
I ran the script to put new data in the data/documents.yaml file.

It should be ok now.
