### ISSUE TITLE
change black background and place text 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#9]
in the tab. Teaching Modules, unit Boder,  you will find the animation, the quiz, the interactive animation and the assignments,  somehow the background of the interactive animation part is black, with white text, I find it difficult to read and would like to change it to normal, 

The text that explains how to use the interactive animation should come first and then the clip, instead of. below the clip 

The literature that is listed below should appear in a separate paragraph, it is now all put together, how can I change this?

**Comment by frederic-reis** [comment]
I put the background in grey and I placed the text above the animation.

To separate the literature, I can put it again below the animation or you can add a title. What do you prefer ?

**Comment by stefaniascagliola** [comment]
I think it belongs to the explanation of the lesson, so put it above the animation, but separate it from the running text, in a table or box?
