### ISSUE TITLE
lesson on Dalimil manuscript should be announced as upcoming 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#92]
I have tried to add UPCOMING to the title of the lesson in UNITS, but it does not show on the website, 
could you handle this?
 
THIS LESSON IS IN PREPARATION 
The Chronicle of Dalimil: a photogenic mediaeval manuscript?

**Comment by frederic-reis** [comment]
The UPCOMING is visible : https://c2dh.github.io/ranketwo/lessons/

To be visible on ranke2.uni.lu, I just need to run the deploy script. It's not automatic.

**Comment by frederic-reis** [comment]
The upcoming is visible !

**Comment by danieleguido** [comment]
Done, udpated ;)

**Comment by stefaniascagliola** [comment]
HI Frederic, 

I have added a few changes in the titles of the Manuscript lesson:

in Eng UPCOMING LESSON, in Fr. LESSON PROCHAINE, in GEr SPATEREN LEKTION,  could you run the script to get it into the real website? 

I will also ask for new translations in Fr and Ger for the beginning of this lesson, 

best
Stefania

**Comment by frederic-reis** [comment]
Hi Stefania,

It's done!
I also fixed an issue on the expert meeting page: the content was duplicated.
