### ISSUE TITLE
language issues 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#94]
HI Fred,

thanks for the changes!!! I received an e-mail  in which a number of mistakes are mentioned:

 "Assignments" is translated as "Zuordnungen" (in other places, more correctly, as "**Aufgaben**")

and "affectations" in French, which doesn't make much sense (better: **"exercises"**). 

I have gone through pages, units, assignments, to find where these wrong terms are used, but could not find any, is there perhaps a kind of Control F for the whole GitHub repository, so that you can trace where 'Affectations' and 'Zurordnungen' are still  used? 

best
Stefania

**Comment by frederic-reis** [comment]
It's done !
It was in the i18n.yaml file.
