### ISSUE TITLE
changes in German names of pages 

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#95]
Hi Fred, 

we have eng , fr and Germ versions of all documents, but I can't find the fr and Ger version of the pages, in data we only have navigation.yaml  in Eng, Noelle sent some corrections which I would like to put through, but I can't find them. 

Startseite
Kritik der digitalen Quellen
Über die Plattform
Über die Lektionen
Gehe sie zu den Lektionen 

Can you let me know? 
best
Stefania

**Comment by frederic-reis** [comment]
It's in `_data/i18n.yaml` file.
