### ISSUE TITLE
change quiz settings

### ISSUE THREAD

**Issue by stefaniascagliola** [C2DH/ranketwo#99]
<iframe width="768" height="597" scrolling="no" src="https://www.playposit.com/play/870433/David-Boders-Interview-collection-2-2-French" frameborder="0"></iframe>

**Comment by frederic-reis** [comment]
Boder English:
https://www.playposit.com/listcode/797374/n717d6/open/anonymous

Boder German:
https://www.playposit.com/listcode/870428/n717d6/open/anonymous

Boder French: https://www.playposit.com/listcode/870433/n717d6/open/anonymous

Transformation:
https://www.playposit.com/listcode/826731/n717d6/open/anonymous

Transformation French:
https://www.playposit.com/listcode/882092/n717d6/open/anonymous

Transformation German:
https://www.playposit.com/listcode/882086/n717d6/open/anonymous

Archival Turn German:
https://www.playposit.com/listcode/881764/n717d6/open/anonymous

**Comment by frederic-reis** [comment]
I changed quiz url.
@stefaniascagliola   Could you test if it's ok ?
